# Generated by Django 3.1.7 on 2021-05-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('task_type', models.IntegerField(choices=[(0, 'Guess the Note'), (1, 'Guess the Chord Key'), (2, 'Guess the Interval')])),
                ('task_sound', models.FileField(upload_to='sounds')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_title', models.CharField(max_length=150)),
                ('exercise_description', models.TextField()),
                ('tasks', models.ManyToManyField(blank=True, to='catalog.Task')),
            ],
        ),
    ]
